### ISSUE TITLE
Integration tests stall

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/spark-client-snap#33] opened 2023-02-17 14:48 UTC
`make integration-tests` stalls the GitHub runner for 6 hours

See: https://github.com/canonical/spark-client-snap/actions/runs/4185273469/jobs/7271619864

**Comment by deusebio** [comment] 2023-02-24 15:52
Thanks @carlcsaposs-canonical for reporting this! Yes, that was caused by a bug in the PR. Spark driver kept on waiting executors to be created, but github runners limited resource did not allow other pod/executors to be instantiated. Configuration for executors not properly set were preventing this. The issue was resolved in the same PR. 

Thus, closing issue now!

**Closed by deusebio** 2023-02-24 15:52 UTC
